# Start from a standard Ubuntu base image to avoid the large CUDA dependencies.
FROM ubuntu:20.04

ARG GENN_VER
LABEL maintainer="J.C.Knight@sussex.ac.uk" \
    version=${GENN_VER} \
    org.opencontainers.image.documentation="https://genn-team.github.io/" \
    org.opencontainers.image.source="https://github.com/genn-team/genn" \
    org.opencontainers.image.title="GeNN CPU Docker image"

# --- NON-INTERACTIVE TIMEZONE FIX ---
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin
# --- END NON-INTERACTIVE TIMEZONE FIX ---

# Set environment variables
ENV GENN_PATH=/opt/genn

# Install necessary tools, Python, pip, build essentials (gcc, g++, make, cmake, git, etc.), and SWIG.
# Git is crucial for the cloning step later.
RUN apt-get update && \
    apt-get upgrade -y && \
    # Configure timezone non-interactively
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get install -yq --no-install-recommends \
        python3-dev python3-pip swig gosu nano libffi-dev pkg-config \
        build-essential cmake git \
        tzdata && \
    # Clean up APT cache to reduce image size
    rm -rf /var/lib/apt/lists/*

# Set python3 to be the default version of python
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Upgrade pip itself and install Python dependencies
RUN python -m pip install --upgrade pip && \
    python -m pip install numpy jupyter matplotlib psutil pybind11

# --- GET GENN SOURCE INSIDE THE CONTAINER ---
RUN mkdir -p ${GENN_PATH}

RUN git clone https://github.com/genn-team/genn.git ${GENN_PATH}

WORKDIR ${GENN_PATH}

# Install GeNN and PyGeNN: GENN_CPU_ONLY=1 forces the build system to only compile the CPU backend.
ENV GENN_CPU_ONLY=1
RUN python3 setup.py develop

# --- COPY YOUR PROJECT CODE ---
WORKDIR /app
COPY back/app /app/app
# Set entrypoint to your execution script (if you have one)
# ENTRYPOINT ["python3", "app/main.py"] 

# Start entrypoint
ENTRYPOINT ["/opt/genn/bin/genn-docker-entrypoint.sh"]

# Default command will be to launch bash
CMD ["/bin/bash"]