version = 5.3.1
archive_dir = /etc/letsencrypt/archive/spike-verse.oriol-tech.com
cert = /etc/letsencrypt/live/spike-verse.oriol-tech.com/cert.pem
privkey = /etc/letsencrypt/live/spike-verse.oriol-tech.com/privkey.pem
chain = /etc/letsencrypt/live/spike-verse.oriol-tech.com/chain.pem
fullchain = /etc/letsencrypt/live/spike-verse.oriol-tech.com/fullchain.pem
[renewalparams]
account = dc24d0a37368aece3aa60f54914468dd
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
