/**
 * GeNN Network Runner Template
 * 
 * This file is compiled TOGETHER with the generated GeNN model code.
 * It has direct access to all GeNN variables and functions.
 * 
 * Generated by SNNverse backend during model build.
 */

#include "definitions.h"  // Generated by GeNN
#include <iostream>
#include <thread>
#include <atomic>
#include <string>
#include <cstring>
#include <set>
#include <mutex>
#include <queue>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/select.h>

// WebSocket++ (asio-based)
#include <websocketpp/config/asio_no_tls.hpp>
#include <websocketpp/server.hpp>

// JSON
#include <nlohmann/json.hpp>

using json = nlohmann::json;
using websocketpp::connection_hdl;

typedef websocketpp::server<websocketpp::config::asio> WsServer;

// Will be filled in by Python template generator
const char* NEURON_METADATA = R"__METADATA__({NEURON_METADATA_JSON})__METADATA__";

class NetworkRunner {
private:
    WsServer ws_server;
    std::set<connection_hdl, std::owner_less<connection_hdl>> ws_connections;
    std::mutex ws_mutex;
    
    int tcp_socket;
    int tcp_port;
    std::atomic<bool> running;
    
    unsigned long long timestep;
    float sim_time;
    const float dt = 0.1f;  // ms
    const int emit_interval = 200;  // emit every 20ms
    
    json metadata;
    
    // State variable storage (generated per model)
    // {TEMPLATE_STATE_VARS}
    
public:
    NetworkRunner(int ws_port, int input_port)
        : tcp_socket(-1), tcp_port(input_port), running(true), timestep(0), sim_time(0.0f) {
        
        // Parse metadata
        metadata = json::parse(NEURON_METADATA);
        
        // Configure WebSocket
        ws_server.init_asio();
        ws_server.set_reuse_addr(true);
        ws_server.set_access_channels(websocketpp::log::alevel::none);
        ws_server.set_error_channels(websocketpp::log::elevel::warn);
        
        ws_server.set_open_handler([this](connection_hdl hdl) {
            std::lock_guard<std::mutex> lock(ws_mutex);
            ws_connections.insert(hdl);
            std::cout << "🔌 Client connected" << std::endl;
            
            // Send metadata
            json msg = {
                {"type", "metadata"},
                {"dt", dt},
                {"voltage_interval_ms", emit_interval * dt},
                {"neurons", metadata["neurons"]}
            };
            ws_server.send(hdl, msg.dump(), websocketpp::frame::opcode::text);
        });
        
        ws_server.set_close_handler([this](connection_hdl hdl) {
            std::lock_guard<std::mutex> lock(ws_mutex);
            ws_connections.erase(hdl);
            std::cout << "🔌 Client disconnected" << std::endl;
        });
        
        ws_server.listen(ws_port);
        ws_server.start_accept();
        
        std::cout << "═══════════════════════════════════════════════════════" << std::endl;
        std::cout << "  GeNN Network Runner" << std::endl;
        std::cout << "═══════════════════════════════════════════════════════" << std::endl;
        std::cout << "🚀 Runner started" << std::endl;
        std::cout << "   WebSocket: port " << ws_port << std::endl;
        std::cout << "   TCP Input: port " << tcp_port << std::endl;
    }
    
    bool start_tcp_server() {
        tcp_socket = socket(AF_INET, SOCK_STREAM, 0);
        if (tcp_socket < 0) {
            std::cerr << "❌ Failed to create TCP socket" << std::endl;
            return false;
        }
        
        int opt = 1;
        setsockopt(tcp_socket, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
        
        struct sockaddr_in addr;
        addr.sin_family = AF_INET;
        addr.sin_addr.s_addr = INADDR_ANY;
        addr.sin_port = htons(tcp_port);
        
        if (bind(tcp_socket, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
            std::cerr << "❌ Failed to bind TCP socket" << std::endl;
            close(tcp_socket);
            return false;
        }
        
        if (listen(tcp_socket, 5) < 0) {
            std::cerr << "❌ Failed to listen" << std::endl;
            close(tcp_socket);
            return false;
        }
        
        // Set non-blocking
        fcntl(tcp_socket, F_SETFL, O_NONBLOCK);
        
        std::cout << "✓ TCP input server listening on port " << tcp_port << std::endl;
        return true;
    }
    
    void run() {
        // Allocate state variable arrays
        // {TEMPLATE_ALLOCATE_VARS}
        
        // Register arrays with GeNN merged groups
        // {TEMPLATE_PUSH_VARS}
        
        // Allocate GeNN memory
        std::cout << "Allocating GeNN model memory..." << std::endl;
        allocateMem();
        std::cout << "✓ Memory allocated" << std::endl;
        
        // Initialize
        std::cout << "Initializing GeNN model..." << std::endl;
        initialize();
        std::cout << "✓ Model initialized" << std::endl;
        
        // Start TCP server
        if (!start_tcp_server()) {
            return;
        }
        
        // Start WebSocket thread
        std::thread ws_thread([this]() {
            ws_server.run();
        });
        
        // Start TCP accept thread
        std::thread tcp_thread([this]() {
            tcp_accept_loop();
        });
        
        // Main simulation loop
        std::cout << "▶️  Starting simulation loop..." << std::endl;
        
        while (running) {
            // Step simulation
            stepTime(timestep, 1);
            timestep++;
            sim_time = timestep * dt;
            
            // Emit updates periodically
            if (timestep % emit_interval == 0) {
                emit_state();
            }
            
            // Small sleep to prevent CPU saturation
            std::this_thread::sleep_for(std::chrono::microseconds(100));
        }
        
        // Cleanup
        ws_server.stop();
        ws_thread.join();
        tcp_thread.join();
        
        if (tcp_socket >= 0) {
            close(tcp_socket);
        }
        
        freeMem();
        std::cout << "✓ Runner stopped" << std::endl;
    }
    
    void tcp_accept_loop() {
        while (running) {
            fd_set read_fds;
            struct timeval tv;
            FD_ZERO(&read_fds);
            FD_SET(tcp_socket, &read_fds);
            tv.tv_sec = 0;
            tv.tv_usec = 100000;  // 100ms
            
            int activity = select(tcp_socket + 1, &read_fds, NULL, NULL, &tv);
            if (activity > 0) {
                struct sockaddr_in client_addr;
                socklen_t client_len = sizeof(client_addr);
                int client_socket = accept(tcp_socket, (struct sockaddr*)&client_addr, &client_len);
                
                if (client_socket >= 0) {
                    std::cout << "🔌 Input provider connected" << std::endl;
                    handle_tcp_client(client_socket);
                    close(client_socket);
                    std::cout << "🔌 Input provider disconnected" << std::endl;
                }
            }
        }
    }
    
    void handle_tcp_client(int client_socket) {
        char buffer[4096];
        std::string accumulated;
        fcntl(client_socket, F_SETFL, O_NONBLOCK);
        
        while (running) {
            fd_set read_fds;
            struct timeval tv;
            FD_ZERO(&read_fds);
            FD_SET(client_socket, &read_fds);
            tv.tv_sec = 0;
            tv.tv_usec = 100000;
            
            int activity = select(client_socket + 1, &read_fds, NULL, NULL, &tv);
            if (activity > 0) {
                ssize_t bytes = recv(client_socket, buffer, sizeof(buffer) - 1, 0);
                if (bytes <= 0) break;
                
                buffer[bytes] = '\0';
                accumulated += buffer;
                
                // Process newline-delimited JSON
                size_t pos;
                while ((pos = accumulated.find('\n')) != std::string::npos) {
                    std::string line = accumulated.substr(0, pos);
                    accumulated = accumulated.substr(pos + 1);
                    
                    if (!line.empty()) {
                        process_input_command(line);
                    }
                }
            }
        }
    }
    
    void process_input_command(const std::string& cmd_str) {
        try {
            json cmd = json::parse(cmd_str);
            std::string type = cmd.value("type", "");
            
            if (type == "stop") {
                std::cout << "⏸️  Stop command received" << std::endl;
                running = false;
            }
            // TODO: Handle spike and current injection based on generated code
        }
        catch (std::exception& e) {
            std::cerr << "❌ Input command error: " << e.what() << std::endl;
        }
    }
    
    void emit_state() {
        // Pull state from device (GPU only)
        // {TEMPLATE_PULL_STATE}
        
        json neurons = json::array();
        
        // Access state variables (generated per model)
        // {TEMPLATE_EMIT_CODE}
        
        json msg = {
            {"type", "voltage"},
            {"t", sim_time},
            {"step", timestep},
            {"neurons", neurons}
        };
        
        broadcast(msg.dump());
    }
    
    void broadcast(const std::string& message) {
        std::lock_guard<std::mutex> lock(ws_mutex);
        for (auto& hdl : ws_connections) {
            try {
                ws_server.send(hdl, message, websocketpp::frame::opcode::text);
            } catch (...) {}
        }
    }
};

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <ws_port> <tcp_port>" << std::endl;
        return 1;
    }
    
    int ws_port = std::stoi(argv[1]);
    int tcp_port = std::stoi(argv[2]);
    
    NetworkRunner runner(ws_port, tcp_port);
    runner.run();
    
    return 0;
}
